project:
  type: website
  output-dir: docs  # Cambiar de _site a docs
 
website:
  title: "Previo Midterm"
  site-url: "https://jorgedelgado13.github.io/previo-midterm/"
  navbar:
    left:
      - href: index.qmd
        text: Home
       
format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    fig-align: center
    embed-resources: true
 